path: src/user
package: pe.lacafetalab.pao.auth.announcement
name: Announcement
properties:
  aggregate:
    id: id
    title: text
    description: text
    authorId: id
    classRoomId: id
    publishAt:
      type: datetime
      required: false
      default: now
message:
  validate:
    valueObject:
      authorId:
        required: "El authorId es requerido"
        valid: "El authorId no es un valor válido"
      classRoomId:
        required: "El classRoomId es requerido"
        valid: "El classRoomId no es un valor válido"
      title:
        required: "El titulo es requerido"
      description:
        required: "La descripcion es requerida"
events:
  created: comunication.announcement.created
repository:
  pk: id
  columnName:
    classRoomId: classroom_id
