path: render.product
pathTest: render.product
nameSpace: app.product
name: Product
properties:
  id: id
  name: string
  code: uuid
  description: string
  createAt: date
  price: number
  isActive: boolean
  category: [books, computers]
